#!/bin/sh

cat <<HEAD
# ACCOUNT SWITCHER PRELUDE
# Sync, refresh
exec sync-mailbox
exec refresh

# Remove all mailboxes.
unmailboxes *

# Remove all relevant variables
unset from
unset realname
unset signature

unset mbox_type
unset mbox
unset folder
unset spoolfile
unset record
unset postponed
unset mask

unset imap_pass
unset smtp_pass

# GPG
unset pgp_default_key
unset pgp_sign_as

# END PRELUDE
HEAD

# Try to switch to the new one
F=~/.mutt/accs.d/"$1".muttrc
DFLT=~/.mutt/acc.dflt

if [ -f "$F" ]; then
	cat -- "$F"
elif [ -f "$DFLT" ]; then
	# Not found, load assigned default instead.
	cat ~/.mutt/accs.d/$(cat "$DFLT").muttrc
else
	# Default.
	first() {
		echo "$1"
	}

	FRST=`first ~/.mutt/accs.d/*.muttrc`
	[ -z "$FRST" ] || cat "$FRST"
fi

cat <<TAIL

# Finish up
push '<change-folder>!<enter>'
TAIL
