#!/bin/sh
# Iterate over the provided directory, catting rc files and running scripts.
[ -z "$1" ] && echo "Usage: $(basename $0) dir" >/dev/stderr && exit 1

for f in "$1"/*; do
	echo "### File: $f ###"

	case "$f" in
		*.muttrc) cat "$f" ;;
		*.sh) . "$f" ;;
	esac
done
