#!/bin/sh
###
## WINDOWCHEF CONFIG FILE.
###

waitron wm_config border_width 4
waitron wm_config internal_border_width 2
waitron wm_config color_focused 0x373737
waitron wm_config color_unfocused 0x070000
waitron wm_config internal_color_focused 0x373737
waitron wm_config internal_color_unfocused 0x070000

waitron wm_config gap_width all 4
waitron wm_config grid_gap_width 4

waitron wm_config cursor_position center

waitron wm_config groups_nr 10
waitron wm_config enable_sloppy_focus true
waitron wm_config enable_resize_hints true
waitron wm_config sticky_windows true
waitron wm_config enable_borders true
waitron wm_config enable_last_window_focusing true
waitron wm_config apply_settings false
waitron wm_config replay_click_on_focus true
waitron wm_config pointer_actions move resize_side resize_corner
waitron wm_config pointer_modifier super
waitron wm_config click_to_focus any
